name: Coverage Badge
on:
  push:
    branches:
      - main
jobs:
  update_badge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: export COLOR=green
      - run: export PERCENT=$(( $RANDOM % 50 + 50 ))  # Generate a random number as example.
      - run: curl https://img.shields.io/badge/coverage-$PERCENT%25-$COLOR > coverage_badge.svg
      - uses: actions/upload-artifact@v3
        with:
          name: main-coverage-badge
          path: coverage_badge.svg
